// <auto-generated />
using MauiCustomerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MauiCustomerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MauiCustomerApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua das Flores, 123",
                            Age = 30,
                            Lastname = "Silva",
                            Name = "João"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Av. Brasil, 456",
                            Age = 25,
                            Lastname = "Santos",
                            Name = "Maria"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua da Paz, 789",
                            Age = 35,
                            Lastname = "Oliveira",
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Av. Central, 321",
                            Age = 28,
                            Lastname = "Costa",
                            Name = "Ana"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rua do Comércio, 654",
                            Age = 42,
                            Lastname = "Ferreira",
                            Name = "Carlos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
